name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  start-dev-server:
    runs-on: ubuntu-latest
    outputs:
      server-url: ${{ steps.start-server.outputs.server-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Start dev server
        id: start-server
        run: |
          yarn run start &
          echo "::set-output name=server-url::http://localhost:8080"

  test:
    runs-on: ubuntu-latest
    needs: start-dev-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright
        run: yarn playwright install --with-deps

      - name: Run end-to-end tests with Playwright (headless)
        run: yarn playwright test --baseUrl ${{ needs.start-dev-server.outputs.server-url }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
